from __future__ import annotations

import html
import json
import zipfile
from uuid import uuid4

import markdown as markdown_lib

from .publishing import compiled_documents
from .storage import project_root


def _chapter_html(content: str) -> str:
    return markdown_lib.markdown(content, extensions=["extra", "sane_lists"])


def preview_payload(
    slug: str,
    *,
    title: str,
    author: str = "",
    trim_width: float = 6.0,
    trim_height: float = 9.0,
) -> dict:
    documents = compiled_documents(slug)
    return {
        "title": title,
        "author": author,
        "trim_width": trim_width,
        "trim_height": trim_height,
        "documents": [
            {
                "title": item["title"],
                "path": item["path"],
                "word_count": item["word_count"],
                "html": _chapter_html(item["content"]),
            }
            for item in documents
        ],
        "words": sum(int(item.get("word_count") or 0) for item in documents),
    }


def _site_html(payload: dict) -> str:
    chapters = payload["documents"]
    chapter_json = json.dumps(
        [{"title": item["title"], "html": item["html"]} for item in chapters],
        ensure_ascii=False,
    ).replace("</", "<\\/")
    title = html.escape(payload["title"])
    author = html.escape(payload.get("author") or "")
    return f"""<!doctype html>
<html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<meta name=\"robots\" content=\"noindex,nofollow\"><title>{title} · Private Preview</title>
<style>
:root{{--paper:#fbf8f1;--ink:#28231f;--muted:#766b62;--accent:#b76536}}
*{{box-sizing:border-box}} body{{margin:0;background:#161312;color:var(--ink);font-family:Georgia,serif}}
header{{position:sticky;top:0;z-index:3;display:flex;gap:1rem;align-items:center;padding:.8rem 1rem;background:#1d1917;color:#f6eee7;border-bottom:1px solid #332a25}}
header strong{{font-family:system-ui,sans-serif}} header small{{color:#b8aaa0}} select{{margin-left:auto;max-width:45vw;background:#2a2421;color:#eee;border:1px solid #4a3b34;padding:.45rem;border-radius:6px}}
.reader{{width:min(44rem,calc(100% - 2rem));min-height:100vh;margin:0 auto;background:var(--paper);padding:4rem 4.2rem 7rem;box-shadow:0 0 40px #0008;line-height:1.72;font-size:1.04rem}}
h1{{text-align:center;font-size:1.9rem;margin:0 0 2.5rem}} p{{margin:0 0 .9em}} blockquote{{border-left:3px solid #b98b6c;padding-left:1rem;color:#5e524a}} hr{{border:0;text-align:center;margin:2rem}} hr:after{{content:'* * *';color:#766b62}}
footer{{padding:1rem;text-align:center;color:#aa9b91;font-family:system-ui,sans-serif;font-size:.8rem}}
@media(max-width:600px){{.reader{{width:100%;padding:2.2rem 1.4rem 5rem;box-shadow:none}} header{{padding:.65rem}} header small{{display:none}}}}
</style></head><body>
<header><strong>{title}</strong><small>{author}</small><select id=\"chapter\"></select></header>
<main class=\"reader\"><h1 id=\"chapterTitle\"></h1><article id=\"content\"></article></main>
<footer>Private preview generated by EmberWriter · host behind authentication for confidential sharing.</footer>
<script>const chapters={chapter_json};const select=document.getElementById('chapter');const titleEl=document.getElementById('chapterTitle');const content=document.getElementById('content');chapters.forEach((c,i)=>{{const o=document.createElement('option');o.value=String(i);o.textContent=c.title;select.appendChild(o)}});function show(i){{const c=chapters[i]||chapters[0];if(!c)return;titleEl.textContent=c.title;content.innerHTML=c.html;location.hash='chapter-'+(i+1)}}select.addEventListener('change',()=>show(Number(select.value)));const start=Math.max(0,(Number((location.hash.match(/chapter-(\\d+)/)||[])[1])||1)-1);select.value=String(start);show(start);</script>
</body></html>"""


def build_preview_site(slug: str, *, title: str, author: str = "") -> dict:
    payload = preview_payload(slug, title=title, author=author)
    root = project_root(slug)
    export_root = root / "exports" / f"preview-site-{uuid4().hex[:10]}"
    export_root.mkdir(parents=True, exist_ok=True)
    index_path = export_root / "index.html"
    index_path.write_text(_site_html(payload), encoding="utf-8")
    readme = export_root / "README.txt"
    readme.write_text(
        "EmberWriter private preview package.\n\n"
        "Open index.html locally to preview. For remote sharing, upload this folder to a host protected "
        "by authentication or another access-control layer. This static package is not itself a security boundary.\n",
        encoding="utf-8",
    )
    zip_path = export_root.with_suffix(".zip")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.write(index_path, arcname="index.html")
        archive.write(readme, arcname="README.txt")
    return {
        "filename": zip_path.name,
        "relative_path": str(zip_path.relative_to(root)).replace("\\", "/"),
        "bytes": zip_path.stat().st_size,
        "documents": len(payload["documents"]),
        "words": payload["words"],
    }
